# Generated by Django 4.1 on 2022-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Скидка'),
        ),
    ]
