# Generated by Django 4.1 on 2022-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discount',
        ),
        migrations.AddField(
            model_name='profile',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Скидка (%)'),
        ),
    ]
