# Generated by Django 4.1 on 2022-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
