# Generated by Django 4.1 on 2022-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_printer_title_alter_toner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='image',
            field=models.ImageField(default='default.png', upload_to='printer_pics'),
        ),
        migrations.AddField(
            model_name='toner',
            name='image',
            field=models.ImageField(default='default.png', upload_to='toner_pics'),
        ),
    ]
