# Generated by Django 4.1 on 2022-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_toner_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='color',
            field=models.BooleanField(default=True, verbose_name='Цветной'),
        ),
    ]
