# Generated by Django 4.1 on 2022-09-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_printer_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория товара'),
        ),
    ]
