# Generated by Django 4.1 on 2022-09-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toner',
            old_name='category',
            new_name='cat',
        ),
        migrations.AddField(
            model_name='toner',
            name='color',
            field=models.CharField(choices=[('C', 'Cyan'), ('M', 'Magenta'), ('Y', 'Yellow'), ('K', 'Black')], default='K', max_length=1, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='toner',
            name='prtr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.printer'),
        ),
    ]
