# Generated by Django 4.1 on 2022-09-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_category_toner_cat_toner_color_toner_prtr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='category',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='toner',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='prtr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.printer', verbose_name='Подходит для принтера'),
        ),
    ]
