# Generated by Django 4.1 on 2022-09-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_category_printer_cat_alter_toner_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner',
            name='prtr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toner_printer', to='shop.printer', verbose_name='Подходит для'),
        ),
    ]
