# Generated by Django 4.1 on 2022-09-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_toner_prtr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
