# Generated by Django 4.1 on 2022-09-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anon_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
