# Generated by Django 4.1 on 2022-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_cart_for_anon_user_remove_cart_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='show_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
