# Generated by Django 4.1 on 2022-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_printer_show_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cart', to='shop.cartproduct'),
        ),
    ]
