# Generated by Django 4.1 on 2022-10-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='specification',
            field=models.FileField(default='default.pdf', upload_to='printer_manuals'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.cartproduct'),
        ),
    ]
