# Generated by Django 4.1 on 2022-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_printer_specification_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Нужна доставка', 'Нужна доставка'), ('Самовывоз', 'Самовывоз')], default='Самовывоз', max_length=100, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработка', 'В обработке'), ('Готов', 'Готов к отгрузке'), ('Выполнен', 'Выполнен')], default='Новый', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
