# Generated by Django 4.1 on 2022-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_order_delivery_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработка', 'В обработке'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Выполнен', 'Выполнен')], default='Новый', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
